"""Micro DM (R50Power) driver package."""

from ao_shaping.drivers.dm.micro.driver import (
    CMD_RELAY_OFF,
    CMD_RELAY_ON,
    CMD_SET_ALL_CHANNEL_VOLTAGE,
    CMD_SET_ALL_VOLTAGE_BY_ARR,
    CMD_SET_CHANNEL_VOLTAGE,
    ControllerStatus,
    FOOTER,
    HEADER,
    MAX_CHANNELS,
    MicroDM,
    MicroDMConnectionError,
    MicroDMError,
    MicroDMVoltageError,
    R50Controller,
    RelayState,
    VOLTAGE_MAX,
    VOLTAGE_MIN,
    WiringMap,
    voltages_to_payload,
)

__all__ = [
    "CMD_RELAY_OFF",
    "CMD_RELAY_ON",
    "CMD_SET_ALL_CHANNEL_VOLTAGE",
    "CMD_SET_ALL_VOLTAGE_BY_ARR",
    "CMD_SET_CHANNEL_VOLTAGE",
    "ControllerStatus",
    "FOOTER",
    "HEADER",
    "MAX_CHANNELS",
    "MicroDM",
    "MicroDMConnectionError",
    "MicroDMError",
    "MicroDMVoltageError",
    "R50Controller",
    "RelayState",
    "VOLTAGE_MAX",
    "VOLTAGE_MIN",
    "WiringMap",
    "voltages_to_payload",
]
